// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrQ1nN-P1y_p4-8M4nb6s8hiYQ9NWCRUs',
    appId: '1:178830511133:web:bb979ca6fca5c299728af4',
    messagingSenderId: '178830511133',
    projectId: 'amba-8809b',
    authDomain: 'amba-8809b.firebaseapp.com',
    storageBucket: 'amba-8809b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqccpVLnW1ikQ83OQj_ESd5E33tS3T-lA',
    appId: '1:178830511133:android:3258518b8f05e14a728af4',
    messagingSenderId: '178830511133',
    projectId: 'amba-8809b',
    storageBucket: 'amba-8809b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlgnqNyA3U-U-3mN9UTHLuwkneG3rEMDk',
    appId: '1:178830511133:ios:ec398a5396b281d8728af4',
    messagingSenderId: '178830511133',
    projectId: 'amba-8809b',
    storageBucket: 'amba-8809b.appspot.com',
    iosClientId: '178830511133-sf0c2kvfcdrps8vnljr2stc1eudfcrl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambaProject',
  );
}
